version: "3.9"
services:
  authService:
    build: ./AuthService/
    container_name: auth-service
    ports:
      - "8080:8080"
    depends_on:
      - database
    ENV:
      SERVER_PORT: 8080
      MYSQQL_HOST: mysql
      MYSQQL_PORT: 3306
      MYSQL_DB: authService
      MYSQL_USER: root
      MYSQL_PASSWORD: admin

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "authService"
    volumes:
      - mysql-data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: admin
    depends_pn:
      - mysql